### ISSUE TITLE
关于README以及编写语言的建议

### ISSUE THREAD

**Issue by fumiama** [MrCai-starter/bilibili#1]
- 建议将项目介绍写详细点，包括详细的使用方法以及示例，这样其他人不必去看代码就知道如何使用了。示例：[yutto](https://github.com/SigureMo/yutto)
- 可以试试用Go语言编写，其编译器可以针对几乎所有平台生成可执行文件，且效率和C语言不相上下。
- 加油d=====(￣▽￣*)b

**Comment by MrCai-starter** [comment]
- 项目介绍我是想着 反正也没人会来用，所以就随便糊了个上来（
- Go语言下学期学，如果我还有心思回来重写就拿Go写一遍XD
- 收到收到收到！[给心心]

**Comment by fumiama** [comment]
- 项目介绍这个我觉得一方面是一种练手，另一方面可以整理自己的思路，让代码在一个蓝图的规划下开发，还是很有必要的。
- 另外关于Go语言，个人认为可以先熟练掌握C（写一个仓库）之后再学，这样可以有一个对比，理解更深一点。当然直接学也完全没有问题。
- Go语言和C语言都注重效率，但是还是很不同的。我的仓库[base16384](https://github.com/fumiama/base16384.git)是用纯C写的，可以试着用Go重写一下代码看一下运行时间。C语言的内联汇编也是优化的一大利器，当然Go也有Plan9的汇编，但是并不是针对某个具体的平台。关于内联汇编的效率提升可以看看我写的[C语言 x86_64处理器下利用gcc内联汇编实现打印char的二进制编码](https://blog.csdn.net/u011570312/article/details/118424834)
